dataset:
  path: /local/scratch/c_adabouei/video_analysis/video_anomaly_detection/UCF_and_Shanghai/UCF-Crime
  i3d_path: /local/scratch/c_adabouei/video_analysis/video_anomaly_detection/UCF_and_Shanghai/UCF-Crime/all_rgbs
  swin_path: /local/scratch/c_adabouei/video_analysis/video_anomaly_detection/UCF_Crime_video_swin_features
  s3d_path: /local/scratch/c_adabouei/video_analysis/dataset/UCF_Crime/S3D
  timesformer_large_path: /local/scratch/c_adabouei/video_analysis/video_anomaly_detection/UCF_Crime_features_timesformer_large
  timesformer_small_path: /local/scratch/c_adabouei/video_analysis/video_anomaly_detection/UCF_Crime_features_timesformer

stage1:
  device: cuda:7
  epochs: 100
  lr_mlp_rgb: 1e-3
  lr_mlp_flow: 1e-3
  lr_t_model: 1e-4
  lr: 1e-4
  weight_decay: 0.001
  train_batch_size: 30
  valid_batch_size: 1

stage2:
  device: cuda:7
  epochs: 100
  lr_mlp_rgb: 1e-3
  lr_mlp_flow: 1e-3
  lr_t_model: 1e-4
  lr: 1e-4
  weight_decay: 0.001
  train_batch_size: 4
  valid_batch_size: 1