dataset:
  path: data/I3D
  i3d_path: data/I3D/all_rgbs
  swin_path: data/VideoSwin
  s3d_path: data/S3D

stage1:
  device: cuda:7
  epochs: 100
  lr_mlp_rgb: 1e-3
  lr_mlp_flow: 1e-3
  lr_t_model: 1e-4
  lr: 1e-4
  weight_decay: 0.001
  train_batch_size: 30
  valid_batch_size: 1

stage2:
  device: cuda:7
  epochs: 100
  lr_mlp_rgb: 1e-3
  lr_mlp_flow: 1e-3
  lr_t_model: 1e-4
  lr: 1e-4
  weight_decay: 0.001
  train_batch_size: 4
  valid_batch_size: 1